# database init, supports postgres too
database=postgres
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost/petclinic}
spring.datasource.username=${DB_USER:petclinic}
spring.datasource.password=${DB_PASS:petclinic}
# SQL is written to be idempotent so this is safe
# spring.sql.init.mode=always
